version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/employee-app
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
